### PR TITLE
Ensure call to LPenHelper is made from the main thread and add inactivity timeout of 100ms before calling it

### LINKED ISSUE #87: Random excel crashes while editing a formula
We have been seeing this randomly from time to time and have just narrowed it down to ExcelDna Intellisense. Heap corruption is reported as Excel crashes. 

The following minidump shows the full callstack and error details [EXCEL.EXE.1956.dmp.zip](https://github.com/Excel-DNA/IntelliSense/files/4165873/EXCEL.EXE.1956.dmp.zip)

Screen Shot 2020-02-06 at 11 05 23

As you can see ExcelDna.IntelliSense is reported in the formula. I'm not able to replicate this issue but it does happen from time to time. I suspect that this won't be enough to help you troubleshoot the issue, is there anything that I could do to help identify and resolve the problem?

### PR DESCRIPTION
**Pull request by gmichaud**
We have deployed this in production to a small subset of our customers and can confirm this fixes #87.

### CODE REVIEW

**Comment by govert** [comment]
Thank you Gabriel - I'll have a look.

**Comment by gmichaud** [comment]
Thanks -- do not hesitate to revert back if you have any feedback or require changes

**Comment by govert** [comment]
I'll try to make a release over the weekend. Thanks you for sorting this out and testing it!

**Comment by govert** [comment]
@gmichaud I've release an update as version 1.4.0 with your changes, and some changes I had queued up. Could you please have a look and let me know if you see any trouble?

**Pull request merged**
